[package]
name = "kanata"
version = "1.5.0-prerelease-1"
authors = ["jtroo <j.andreitabs@gmail.com>"]
description = "Multi-layer keyboard customization"
keywords = ["cli", "linux", "windows", "keyboard", "layout"]
categories = ["command-line-utilities"]
homepage = "https://github.com/jtroo/kanata"
repository = "https://github.com/jtroo/kanata"
readme = "README.md"
license = "LGPL-3.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = [ "std", "derive", "help", "suggestions" ], default_features = false }
log = { version = "0.4.8", default_features = false }
simplelog = "0.12.0"
anyhow = "1"
parking_lot = "0.12"
once_cell = "1"
serde = { version = "1", features = ["alloc", "derive"], default_features = false }
serde_json = { version = "1", features = ["alloc"], default_features = false }
radix_trie = "0.2"
rustc-hash = "1.1.0"
miette = { version = "5.7.0", features = ["fancy"] }
dirs = "5.0.1"

# Pinned to avoid including multiple versions of a dependency
is-terminal = "=0.4.7"
# Pinned to avoid downloading and running binary blobs on Linux
serde_derive = "=1.0.171"

# kanata-keyberon = "0.150.0"
# kanata-parser = "0.150.0"
# Uncomment below and comment out above for testing local changes.
# Otherwise any changes to the local files will not reflect in the compiled
# binary.
kanata-keyberon = { path = "keyberon" }
kanata-parser = { path = "parser" }

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "=0.12.0"
signal-hook = "0.3.14"
inotify = { version = "0.10.0", default_features = false }
mio = { version = "0.8.4", features = ["os-poll", "os-ext"] }
nix = { version = "0.26.1", features = ["ioctl"] }
sd-notify = "0.4.1"

[target.'cfg(target_os = "windows")'.dependencies]
encode_unicode = "0.3.6"
winapi = { version = "0.3.9", features = [
    "wincon",
    "timeapi",
    "mmsystem",
] }
native-windows-gui = { version = "1.0.12", default_features = false }
kanata-interception = { version = "0.2.0", optional = true }

[features]
cmd = ["kanata-parser/cmd"]
perf_logging = []
interception_driver = ["kanata-interception", "kanata-parser/interception_driver"]

[profile.release]
opt-level = "z"
lto = "fat"
panic = "abort"
codegen-units = 1
