[package]
name = "kanata"
version = "1.0.0"
authors = ["jtroo <j.andreitabs@gmail.com>"]
description = "Multi-layer keyboard customization"
keywords = ["cli", "linux", "windows", "keyboard", "layout"]
categories = ["command-line-utilities"]
homepage = "https://github.com/jtroo/kanata"
repository = "https://github.com/jtroo/kanata"
readme = "README.md"
license = "LGPL-3.0"
edition = "2021"

[dependencies]
libc = "0.2.70"
clap = { version = "3", features = [ "derive" ] }
log = "0.4.8"
simplelog = "0.8.0"
anyhow = "1"
parking_lot = "0.12"
crossbeam-channel = "0.5"
once_cell = "1"

# Using my personal fork for tap_hold_interval and Sequence
kanata-keyberon = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
evdev-rs = "0.4.0"
uinput-sys = "0.1.7"

[target.'cfg(target_os = "windows")'.dependencies]
encode_unicode = "0.3.6"
winapi = { version = "0.3.9", features = ["consoleapi", "wincon"] }
native-windows-gui = { version = "1.0.12", features = [
    "cursor",
    "embed-resource",
    "menu",
    "message-window",
    "no-styling",
] }
