[package]
name = "kanata"
version = "1.0.7"
authors = ["jtroo <j.andreitabs@gmail.com>"]
description = "Multi-layer keyboard customization"
keywords = ["cli", "linux", "windows", "keyboard", "layout"]
categories = ["command-line-utilities"]
homepage = "https://github.com/jtroo/kanata"
repository = "https://github.com/jtroo/kanata"
readme = "README.md"
license = "LGPL-3.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = [ "derive" ] }
log = "0.4.8"
simplelog = "0.12.0"
anyhow = "1"
parking_lot = "0.12"
crossbeam-channel = "0.5"
once_cell = "1"
kanata-keyberon = { git = "https://github.com/Philipp-M/keyberon.git", branch = "coord-u8-to-u16" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
net2 = "0.2"
radix_trie = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.12.0"
signal-hook = "0.3.14"
mio = { version = "0.8.4", features = ["os-poll", "os-ext"] }

[target.'cfg(target_os = "windows")'.dependencies]
encode_unicode = "0.3.6"
winapi = { version = "0.3.9", features = [
    "wincon",
    "timeapi",
    "mmsystem",
] }
native-windows-gui = "1.0.12"
interception = { version = "0.1.2", optional = true }

[features]
cmd = []
interception_driver = [ "interception" ]

[profile.release]
opt-level = "z"
lto = "fat"
